$(document).ready(function(){
	$('.owl-1').owlCarousel({
    loop:true,
    margin:0,
    nav:false,
    dots:false,
    autoplay:true,
	autoplayTimeout:3000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
	})
    $('.owl-2').owlCarousel({
    loop:true,
    margin:20,
    nav:false,
    dots:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:3
        }
    }
    })
    $('.owl-3').owlCarousel({
    loop:true,
    margin:0,
    nav:true,
    dots:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
    })
    $(".best").click(function(){
        $(this).addClass("active1")
        $(".menu1").addClass("show")
        $(".appetizers").removeClass("active1")
        $(".menu3").removeClass("show")
        $(".soups").removeClass("active1")
        $(".menu2").removeClass("show")
    })
    $(".soups").click(function(){
        $(".appetizers").removeClass("active1")
        $(".menu3").removeClass("show")
        $(".best").removeClass("active1")
        $(".menu1").removeClass("show")
        $(this).addClass("active1")
        $(".menu2").addClass("show")
    })
    $(".appetizers").click(function(){
        $(".soups").removeClass("active1")
        $(".menu2").removeClass("show")
        $(".best").removeClass("active1")
        $(".menu1").removeClass("show")
        $(this).addClass("active1")
        $(".menu3").addClass("show")
    })
});